<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
<style type="text/css">
	.errorMsg {
		font-family: 'Open Sans',"Helvetica Neue",Helvetica,Arial,sans-serif;
		color: #B94A48;
	}
</style>
<div>
	<ul class="breadcrumb">
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'media', 'action' => 'list-media')); ?>">Manage Video</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="#">Create Video</a>
		</li>
	</ul>
</div>
			
<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title style="cursor:pointer;">
			<h2><i class="icon-facetime-video"></i> Create Video</h2>
			<div class="box-icon">
			</div>
		</div>
		<div class="box-content">

<?php	$form = $this->createMediaForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'media', 'action' => 'create-media')));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
			  <fieldset>
			  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
				<?php	echo $this->formHidden($form->get('_id'));	?>
				<input type="Hidden" id="video-length" name="video-length">
				<div class="control-group">
					<label class="control-label" for="mediaName">Title</label>
					<div class="controls">
						<?php	echo $this->formRow($form->get('media_title')); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="mediaLink">URL</label>
					<div class="controls">
						<?php	echo $this->formRow($form->get('media_url')); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="mediaCategory">Category</label>
					<div class="controls">
						<?php	$tempArray		= array();
								$tempArray['']	= 'Select Category';
								foreach($this->categoryArray as $key => $value) {
									$id				= (string)$value['_id'];
									$tempArray[$id]	= $value['category_name'];
								}	?>
						<?php	echo $this->formRow($form->get('media_category')->setAttributes(array('id' => 'media_category'))->setValueOptions($tempArray)); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="mediaDescription">Description</label>
					<div class="controls" id="media_description_div">
						<?php	echo $this->formRow($form->get('media_description')); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="mediaTag">Tags</label>
					<div class="controls">
						<?php	$tempTagsArray		= array();
								foreach($this->tagsArray as $key => $value) {
									$id				= (string)$value['_id'];
									$tempTagsArray[$id]	= $value['tag_name'];
								}	?>
						<?php	echo $this->formRow($form->get('media_tags')->setAttributes(array('id' => 'media_tags', 'data-rel' => 'chosen', 'multiple' => 'multiple'))->setValueOptions($tempTagsArray)); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="visibilityStatus">Approved</label>
					<div class="controls">
					  <?php	echo $this->formRow($form->get('media_approved')); ?>
					   <span id="radioError"></span>
					</div>
				 </div>
				<div class="control-group">
					<label class="control-label" for="visibilityStatus">Visibility Status</label>
					<div class="controls">
					  <?php	echo $this->formRow($form->get('media_status')); ?>
					   <span id="radioError"></span>
					</div>
				 </div>
				<div class="form-actions">
				  	<?php	echo $this->formSubmit($form->get('submit')); ?>
					<?php	echo $this->formReset($form->get('reset')); ?>
				</div>
			  </fieldset>
<?php	echo $this->form()->closeTag();	?> 

		</div>
	</div><!--/span-->
</div><!--/row-->
<script type="text/javascript">
//	Start: Textarea - Editor
	$(window).load(function(){	//	$('.textarea_tabs').click(function(){
		$('.cleditorMain iframe').css('height', '197px');
		$('.cleditorToolbar').css('height', '53px');
		$('.cleditorButton').css('background-color', 'transparent');
		$('.cleditorDisabled').removeAttr('disabled');
		$('.cleditorMain div').each(function(){
			$(this).removeClass('cleditorDisabled');
		});
		$('#uniform-media_approved').children().css('margin-top', '3px');
	});
//	End
	var descFlag	= 0;
	var validFlag	= 0;
	
	function validateDesc() {
		$('#descErrorMsg').remove();
		var contentInc = 0;
		$('#media_description').each(function(){
			var message	= '';
			var contenttabname	= $(this).attr('name');
			var description	= $.trim($(this).val());
			description	= description.replace(/&nbsp;/g, ' ');
			description	= description.replace(' ', '');
			
			if(description == '' || (description.length == 4 && description == '<br>'))
				message	= 'Please Enter the Media Description';
			else if(description.length > 5000)
				message	= 'Media Description should not exceed 5000 characters';
			
			if(description == '' || description == '<br>' || description.length > 5000) {
				$('div #media_description_div').find('.cleditorMain').after('<span id="descErrorMsg" class="help-inline errorMsg">' + message + '</span>');
				$('div #media_description_div .cleditorMain').css({'border-color':'#B94A48', 'color':'#B94A48'});
				//	For cursor focus
				var iframeId	= 'currentContent' + contentInc;
				$('div #media_description_div .cleditorMain iframe').attr('id', iframeId);
				if(descFlag == 0)
					$('#'+iframeId).focus();
				
				validFlag = 1;
				return false;
			} else {
				$('div #media_description_div .cleditorMain').css({'border-color':'#CCCCCC', 'color':'#888888'});
				validFlag	= 0;
			}
			contentInc++;
		});
		
		if(descFlag == 0 && validFlag == 0) {
			return true;
		} else {
			return false;
		}
	}
	
	/*	function findDuration() {
		$.ajax({
			type: "POST",
		    url: '/cms/media/fetch-video-length',
		    data: '',
		    success: function (respomse) {
				$('#video-length').val(respomse);
				return true;
			}
		});
		//return false;
	}	*/

</script>