<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
<div>
	<ul class="breadcrumb">
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'media', 'action' => 'list-tag')); ?>">Manage Tag</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="#">Edit Tag</a>
		</li>
	</ul>
</div>
			
<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title style="cursor:pointer;">
			<h2><i class="icon-th-large"></i> Create Tag</h2>
			<div class="box-icon">
			</div>
		</div>
		<div class="box-content">

<?php	$form = $this->createTagForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'media', 'action' => 'edit-tag', 'id' => $this->tagid)));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
			  <fieldset>
			  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
				<?php	echo $this->formHidden($form->get('_id'));	?>
				<div class="control-group">
					<label class="control-label" for="carrierName">Tag Name</label>
					<div class="controls">
						<?php	echo $this->formRow($form->get('tag_name')); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="carrierStatus">Tag Status</label>
					<div class="controls">
					  <?php	echo $this->formRow($form->get('tag_status')); ?>
					   <span id="radioError"></span>
					</div>
				 </div>
				<div class="form-actions">
				  	<?php	echo $this->formSubmit($form->get('submit')); ?>
					<?php	echo $this->formReset($form->get('reset')); ?>
				</div>
			  </fieldset>
<?php	echo $this->form()->closeTag();	?> 

		</div>
	</div><!--/span-->
</div><!--/row-->
