<?php	echo $this->render('leftnav.phtml');	?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		
		$messageClass	= 'alert-success';
		
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>

		<div>
			<ul class="breadcrumb">
				<li>
					<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'dashboard')); ?>">Home</a> <span class="divider">/</span>
				</li>
				<li>
					<a href="<?php	echo $this->url('cms', array('controller' => 'media', 'action' => 'list-media')); ?>">Manage Video</a> <span class="divider">/</span>
				</li>
				<li>
					<a href="#">List Video Messages</a>
				</li>
			</ul>
		</div>

		<div style="float:left; width: 100%;">
			<div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
		</div>
		
		<div class="row-fluid" id="listingDiv"></div>

<script type="text/javascript">
	loadDiv('listingDiv', '/cms/media/view-media-message', '', '');
</script>