	<div class="box span12">
		<?php	if(count($records) > 0) { ?>
		<div class="box-header well" data-original-title style="cursor:pointer;">
			<h2><i class="icon-list-alt"></i> List Video</h2>
			<div class="box-icon">
			</div>
		</div>
		<div class="box-content">
			<div class="row-fluid">
				<div class="span6" style="padding-bottom:6px">
					<div id="DataTables_Table_0_length" class="dataTables_length">
						<label>
							<select name="DataTables_Table_0_length" size="1" aria-controls="DataTables_Table_0" onchange='callPerPage("media-listcount", this.value);'>
								<option value="10" <?php	if($this->perPage == 10) echo 'selected="selected"' ?>>10</option>
								<option value="25" <?php	if($this->perPage == 25) echo 'selected="selected"' ?>>25</option>
								<option value="50" <?php	if($this->perPage == 50) echo 'selected="selected"' ?>>50</option>
								<option value="100" <?php	if($this->perPage == 100) echo 'selected="selected"' ?>>100</option>
							</select> records per page</label>
					</div>
				</div>
				<div class="span6" style="display:none;">
					<div class="dataTables_filter" id="DataTables_Table_0_filter">
						<label style="display: none;">Search: <input type="text" aria-controls="DataTables_Table_0"></label>
					</div>
				</div>
			</div>
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
			  <thead>
				  <tr>
					  <th style="cursor:pointer;" width="15%" onclick="loadDiv('listingDiv', '/media-list', 'media_title', '<?php	if($this->sortBy == 'media_title') { echo '1'; } else { echo '0'; } ?>');">Video Title</th>
					  <th style="cursor:pointer;" width="10%" onclick="loadDiv('listingDiv', '/media-list', 'media_category', '<?php	if($this->sortBy == 'media_category') { echo '1'; } else { echo '0'; } ?>');">Category</th>
						<th style="cursor:pointer;" width="10%" onclick="loadDiv('listingDiv', '/media-list', 'date_added', '<?php	if($this->sortBy == 'date_added') { echo '1'; } else { echo '0'; } ?>');">Created Date</th>
						<th style="cursor:pointer;" width="10%" onclick="loadDiv('listingDiv', '/media-list', 'date_modified', '<?php	if($this->sortBy == 'date_modified') { echo '1'; } else { echo '0'; } ?>');">Modified Date</th>
					  <th style="cursor:pointer;" width="5%" onclick="loadDiv('listingDiv', '/media-list', 'media_approved', '<?php	if($this->sortBy == 'media_approved') { echo '1'; } else { echo '0'; } ?>');">Approval Status</th>
					  <th style="cursor:pointer;" width="5%" onclick="loadDiv('listingDiv', '/media-list', 'media_status', '<?php	if($this->sortBy == 'media_status') { echo '1'; } else { echo '0'; } ?>');">Visibility</th>
					  <th width="40%">Actions</th>
				  </tr>
			  </thead>   
			  <tbody>
			  <?php	//	Category
			  		$tempArray		= array();
					foreach($this->categoryArray as $key => $value) {
						$id				= (string)$value['_id'];
						$tempArray[$id]	= $value['category_name'];
					}
					//	Tags
					$tempTagArray	= array();
					foreach($this->tagsArray as $key => $value) {
						$id					= (string)$value['_id'];
						$tempTagArray[$id]	= $value['tag_name'];
					}
					//	Users
					$tempUserArray	= array();
					foreach($this->usersArray as $key => $value) {
						$id					= (string)$value['_id'];
						$tempUserArray[$id]	= $value['user_firstname'].' '.$value['user_lastname'];
					}	?>

<?php				foreach($records as $key => $row) : ?>
				<tr>
					<td><?php	if(strlen($row['media_title']) > 20) echo substr($row['media_title'], 0, 20) . '...'; else echo $row['media_title']; ?></td>
					<td><?php	if(strlen($tempArray[$row['media_category']]) > 20) echo substr($tempArray[$row['media_category']], 0, 20) . '...'; else echo $tempArray[$row['media_category']]; ?></td>
					<td class="center">
						<span><?php	if(isset($row['date_added']) && $row['date_added'] != '') echo date('m/d/Y H:i:s', $row['date_added']); else echo '00/00/0000 00:00:00'; ?></span>
					</td>
					<td class="center">
						<span><?php	if(isset($row['date_modified']) && $row['date_modified'] != 0) echo date('m/d/Y H:i:s', $row['date_modified']); else echo '00/00/0000  00:00:00'; ?></span>
					</td>
					<td class="center">
						<span><?php	if($row['media_approved'] == 0) echo 'Pending'; else echo 'Approved'; ?></span>
					</td>
					<td class="center">
						<span><?php	if($row['media_status'] == 0) echo 'Inactive'; else echo 'Active'; ?></span>
					</td>
<?php				$recordId	= (string)$row['_id']; ?>
<?php				$mediaTags	= '';
					if(is_array($this->mediaTagsArray) && count($this->mediaTagsArray) > 0) {
						foreach($this->mediaTagsArray as $ikey => $ivalue) {
							if($ivalue['media_id'] == $recordId) {
								$mediaTags	.= (isset($tempTagArray[$ivalue['tag_id']])) ? $tempTagArray[$ivalue['tag_id']].', ' : '';
							}
						}
					}
					$mediaTags				= ($mediaTags != '') ? substr($mediaTags, 0, -2) : '';
					$tempDescriptionText	= trim(preg_replace('/\s\s+/', ' ', $row['media_description']));	?>
					<td class="center">
						<a class="btn btn-success view-user" href="#" 
							onclick='setMediaValues("<?php	echo addslashes(str_replace(array("'", '"'), array('&lsquo;', '&ldquo;'), $row['media_title'])); ?>", "<?php	echo $row['media_url']; ?>", "<?php echo $tempArray[$row['media_category']]; ?>", "<?php echo addslashes(str_replace(array("'", '"', '“'), array('&lsquo;', '&ldquo;', '&ldquo;'), $tempDescriptionText)); ?>", "<?php	if($row['media_approved'] == 1) echo 'Approved'; else echo 'Pending'; ?>", "<?php	if($row['media_status'] == 1) echo 'Active'; else echo 'Inactive'; ?>", "<?php if(isset($row['approved_user_id']) && isset($tempUserArray[$row['approved_user_id']])) echo $tempUserArray[$row['approved_user_id']]; ?>", "<?php echo date('m/d/Y H:i:s', $row['date_approved']); ?>", "<?php echo date('m/d/Y H:i:s', $row['date_added']); ?>", "<?php if(isset($row['user_id']) && isset($tempUserArray[$row['user_id']])) echo $tempUserArray[$row['user_id']]; ?>", "<?php echo $mediaTags; ?>");'>
							<i class="icon-zoom-in icon-white"></i>  
							View                                            
						</a>
						<a class="btn btn-info"  style="background:gray" href="<?php	echo $this->url('cms', array('controller' => 'media', 'action' => 'list-media-message', 'id' => $recordId)); ?>" >
							<i class="icon-envelope icon-white"></i> View Messages
						</a>
						<a class="btn btn-info" href="<?php	echo $this->url('cms', array('controller' => 'media', 'action' => 'edit-media', 'id' => $recordId)); ?>">
							<i class="icon-edit icon-white"></i>  
							Edit                                            
						</a>
						<a class="btn btn-danger" style="cursor:pointer;" onclick="deleteMedia('<?php	echo $row['_id']; ?>', '<?php	if(count($records) > 1) { echo $this->page; } else { echo ($this->page - 1); } ?>');">
							<i class="icon-trash icon-white"></i> 
							Delete
						</a>
					</td>
				</tr>
				<?php	endforeach; ?>							
			  </tbody>
		  </table>          
		</div>
		<?php		$url = $this->url('cms', array('controller' => 'media', 'action' => 'view-media'));
					if(count($records) > 0) {
						//handle parameter get :)
						$parameterGet = '';	//$parameterGet = $this->Requesthelper();
						if ($parameterGet != "") {
							$parameterGet = "?".$parameterGet;
						}	?>
						<div id="DataTables_Table_0_info" class="dataTables_info" style="padding-left: 15px;">Showing <?php	echo (($page - 1) * $perPage) + 1; ?> to <?php	if(($page * $perPage) < $totalRecords) echo ($page * $perPage); else echo $totalRecords; ?> of <?php	echo $totalRecords; ?> entries</div>
							<div class="span12 center">
								<div class="dataTables_paginate paging_bootstrap pagination">
									<ul>
								      <?php if ($page > 1): ?>
									  <li class="prev"><a href='#' onclick="loadDiv('listingDiv', '<?php echo $url.'/'.($page-1).$parameterGet; ?>', '', '');"><< Previous</a></li>
								      <?php else: ?>
									  <li class="prev disabled"><a href="#"><< Previous</a></li>
								      <?php endif; ?>
<?php										for($inc = 1; $inc <= ceil($totalRecords / $perPage); $inc++) {	?>
								      <?php if ($page != $inc): ?>
								      <li ><a href='#' onclick="loadDiv('listingDiv', '<?php echo $url.'/'.$inc.$parameterGet; ?>', '', '');"><?php echo $inc; ?></a></li>
								      <?php else: ?>
									  <li class="active"><a href="#"><?php echo $inc; ?></a></li>
								      <?php endif; ?>
								      <?php } ?>
								      <?php if ($page < ceil($totalRecords / $perPage)): ?>
									  <li class="next"><a href="#" onclick="loadDiv('listingDiv', '<?php echo $url.'/'.($page+1).$parameterGet; ?>', '', '');">Next >> </a></li>
									  <?php else: ?>      	
									  <li class="next disabled"><a href="#">Next >> </a></li>
								      <?php endif; ?>
							    	</ul>
								</div>
							</div>
		<?php		}
				} else { ?>
		<div style="text-align:center;padding-top:3px">
		  	No Records found.
		</div>
		<?php	} ?>
	</div>
	