<?php	if(is_array($records) && count($records) > 0) {
			foreach($records as $key => $value) {
				$videoUrl	= '/video/'.base64_encode((string)$value['_id']);	?>
	<dd class="col-md-4 col-xs-12 videoFrame" id="dd<?php	echo $key; ?>">
		<div class="row">
        	<div class="col-md-12 col-xs-6">
            	<div class="video">
					<a href="<?php	echo $videoUrl; ?>" title="<?php echo $value['media_title']; ?>">
                     <img src="http://img.youtube.com/vi/<?php echo $this->customurl($value['media_url'], 'fetchYoutubeID'); ?>/0.jpg" alt="<?php echo $value['media_title']; ?>" >
					 <span class="play-btn"><i class="fa fa-play fa-2"></i></span>
					</a>
                     <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
				</div>
			</div>
            <div class="col-md-12 col-xs-6">
				<h4><a title="<?php echo $value['media_title']; ?>" href="<?php	echo $videoUrl; ?>"><?php	echo $this->text($value['media_title'], 25, 'displayText'); ?></a></h4>
            	<!-- <h4 ><a href="http://vimeo.com/75542539"><?php	echo $this->text($value['media_title'], 25, 'displayText'); ?></a></h4> -->
				<div class="row">
                	<div class="col-md-5 col-xs-12 pull-right">
                    	<ul class="likes">                        	
                        	<li><a href="#" class="like" onclick='dovote(1, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                            <li><a href="#" class="dislike" onclick='dovote(2, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                            <li><a href="#" class="p-delete" onclick='deletePlaylistMedia("<?php	echo $key; ?>");'><i class="fa fa-2x fa-trash-o"></i></a></li>
						</ul>
					</div>
                    <div class="col-md-7 col-xs-12 pull-left">
                    	<ul class="users">
<?php						if(isset($extended['media'][(string)$value['_id']]) && is_array($extended['media'][(string)$value['_id']]) && count($extended['media'][(string)$value['_id']]) > 0) {
								$inc 	= 0;
								$userCount	= count($extended['media'][(string)$value['_id']]);
								$iuserCount	= ($userCount > 4) ? 3 : 4;
								foreach($extended['media'][(string)$value['_id']] as $ikey => $ivalue) {
									if($inc < $iuserCount) {
										
										$userPhoto	= (isset($extended['friends'][$ivalue]['user_photo']) && trim($extended['friends'][$ivalue]['user_photo']) != '') ? '/Front/users/photo/thumb/'.$extended['friends'][$ivalue]['user_photo'] : '/Front/users/photo/thumb/no_photo.png';
										$userPhoto	= (file_exists(getcwd().'/public/'.$userPhoto)) ? $userPhoto : '/Front/users/photo/thumb/no_photo.png'; ?>
                        	<li><a href="#"><img src="<?php echo $userPhoto; ?>" width="30" height="30" alt="<?php echo ucwords($extended['friends'][$ivalue]['user_firstname'].' '.$extended['friends'][$ivalue]['user_lastname']); ?>" title="<?php echo ucwords($extended['friends'][$ivalue]['user_firstname'].' '.$extended['friends'][$ivalue]['user_lastname']); ?>"></a></li>
<?php								}
									$inc++;
								}
								if(count($extended['media'][(string)$value['_id']]) > 4) {	?>
							<li class="more"><a href="#" onclick="showExtendedFriends('<?php echo (string)$value['_id']; ?>');return false;">4+</a></li>
<?php							}
							} else { ?>
							<li><a href="#" style="opacity:0;"></a></li>
<?php						} ?>
						</ul>                                                
					</div>
				</div>
			</div>
		</div>
	</dd>
<?php		}
			if(($totalRecords - ($page * PERPAGE)) > 0) {	?>
				<dd class="clearfix videoMore" id="more_videos">
                    <p class="btn btn-default" onclick="loadPlaylistVideos(1);">show 18 more</p>
                </dd>
<?php		} else { ?>
				<dd class="clearfix videoMore" id="no_more_videos">
                    <p class="btn nomore-btn">No more videos</p>
                </dd>
<?php		}
		} else { ?>
			
			<dd class="col-md-4 col-xs-12 videoFrame">
				<div class="row">
		        	<div class="col-md-12 col-xs-6">
					No videos found
					</div>
				</div>
			</dd>
			<div style="height:100px;"></div>
			
<?php	} ?>
<script type="text/javascript">
	if($('#video_count').length > 0) {
		$('#video_count').html('<?php echo $totalRecords; ?> videos found');
	}
</script>