<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'change-password')); ?>">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Change Password</a>
					</li>
				</ul>
			</div>
			
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well" data-original-title style="cursor:pointer;">
						<h2><i class="icon-edit"></i> Change Password</h2>
						<div class="box-icon">
						</div>
					</div>
					<div class="box-content">
<?php	$form = $this->changePasswordForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'user', 'action' => 'change-password')));
		$form->setAttribute('name', 'changePasswordForm');
		$form->prepare();
		echo $this->form()->openTag($form);	?>
						  <fieldset>
						   <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
						  	
							<div class="control-group">
								<label autofocus class="control-label" for="password">Old Password</label>
								<div class="controls">
									<?php	echo $this->formRow($form->get('password')); ?>
								</div>
							</div>
							<div class="control-group">
							  <label class="control-label" for="newpassword">New Password</label>
							  <div class="controls">
								<?php	echo $this->formRow($form->get('newpassword')); ?>
							  </div>
							</div>
							<div class="control-group">
							  <label class="control-label" for="confirmpassword">Confirm Password</label>
							  <div class="controls">
								<?php	echo $this->formRow($form->get('confirmpassword')); ?>
							  </div>
							</div>
							<div class="form-actions">
							  <?php	echo $this->formSubmit($form->get('submit')); ?>
							  <?php	echo $this->formReset($form->get('cancel')); ?>
							</div>
						  </fieldset>
<?php	echo $this->form()->closeTag();	?> 
					</div>
				</div>
			</div>
