<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	
		?>
<div>
	<ul class="breadcrumb">
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'list-group')); ?>">Manage User Group</a> <span class="divider">/</span>
		</li>
		<li>
			<a href="#">Edit User Group</a>
		</li>
	</ul>
</div>
			
<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title style="cursor:pointer;">
			<h2><i class="icon-th-large"></i> Edit User Group</h2>
			<div class="box-icon">
			</div>
		</div>
		<div class="box-content">
<!-- Start: Create User Form -->
<?php	$form = $this->createGroupForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'user', 'action' => 'edit-group', 'id' => $this->groupid)));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
			  <fieldset>
			  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
				<?php	echo $this->formHidden($form->get('_id'));	?>
				<div class="control-group">
					<label class="control-label" for="carrierName">Group Name</label>
					<div class="controls">
						<?php	echo $this->formRow($form->get('group_name')); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="carrierName">Role</label>
					<div class="controls">
						<?php	$tempArray		= array();
								$tempArray['']	= 'Select Role';
								foreach($this->rolesArray as $key => $value) {
									$id				= (string)$value['_id'];
									$tempArray[$id]	= $value['role_name'];
								}	?>
						<?php	echo $this->formRow($form->get('group_role')->setAttributes(array('id' => 'group_role'))->setValueOptions($tempArray)); ?>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="carrierStatus">Group Status</label>
					<div class="controls">
					  <?php	echo $this->formRow($form->get('group_status')); ?>
					   <span id="radioError"></span>
					</div>
				 </div>
				<div class="form-actions">
				  	<?php	echo $this->formSubmit($form->get('submit')); ?>
					<?php	echo $this->formReset($form->get('reset')); ?>
				</div>
			  </fieldset>
<?php	echo $this->form()->closeTag();	?> 

		</div>
	</div><!--/span-->

</div><!--/row-->

