<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'list-user')); ?>">Manage User</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Create User</a>
					</li>
				</ul>
			</div>
			
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well" data-original-title style="cursor:pointer;">
						<h2><i class="icon-user"></i> Edit User</h2>
						<div class="box-icon">
						</div>
					</div>
					<div class="box-content">
<!-- Start: Create User Form -->
<?php	$form = $this->createUserForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'user', 'action' => 'edit-user', 'id' => $this->userid)));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
						  <fieldset>
						  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> <?php	echo $this->message; ?></div>
						  	<?php	echo $this->formHidden($form->get('_id')); ?>
							<div class="control-group">
								<label class="control-label" for="firstName">First Name</label>
								<div class="controls">
									<?php	echo $this->formRow($form->get('user_firstname')); ?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="lastName">Last Name</label>
								<div class="controls">
									<?php	echo $this->formRow($form->get('user_lastname')); ?>
								</div>
							</div>
							<div class="control-group">
								  <label class="control-label" for="userEmail">Email address</label>
								  <div class="controls">
									  <?php	echo $this->formRow($form->get('user_email')); ?>
								  </div>
							</div>
							
							<div>
								<div class="box-icon" style="float: left; width: 150px; margin-top: -40px; margin-left: 386px;">
									<span class="label" style="vertical-align:text-bottom;cursor:pointer;"  onclick="clickDiv('logo_toggle_class');">Change Password</span>
									<a class="btn btn-minimize btn-round" href="#"><i id="logo_toggle_class" class="icon-chevron-down"></i></a>
								</div>
							</div>
							<div class="box-content" style="display: none;" id="logo_toggle">
							
							<div class="control-group">
								<label class="control-label" for="password">Password</label>
								<div class="controls">
									<?php	echo $this->formRow($form->get('user_password')); ?>
								</div>
							</div>
							
							</div>
							<div class="control-group">
								<label class="control-label" for="user_group">User Group</label>
								<div class="controls">
								
								<?php	$tempArray		= array();
										$tempArray['']	= 'Select User Group';
										foreach($groupArray as $key => $value) {
											$id				= (string)$value['_id'];
											$tempArray[$id]	= $value['group_name'];
										}	?>
								<?php	//echo $this->formRow($form->get('user_group'));	?>
								
								
								<?php	echo $this->formRow($form->get('user_group')->setAttributes(array('id' => 'user_group'))->setValueOptions($tempArray));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="fbuid">Facebook UID</label>
								<div class="controls">
									<?php	echo $this->formRow($form->get('user_fbuid')); ?>
								</div>
							</div>
							<div class="control-group">
							  <label class="control-label" for="user_dob">Date of Birth</label>
							  <div class="controls">
								<?php	echo $this->formRow($form->get('user_dob')); ?>
								   <span id="radioError"></span>
							  </div>
							</div>
							<div class="control-group">
								<label class="control-label" for="user_gender">Gender</label>
								<div class="controls">
								  <?php	echo $this->formRow($form->get('user_gender')); ?>
								   <span id="radioError"></span>
								</div>
							 </div>
							<div class="control-group">
								<label class="control-label" for="userStatus">Status</label>
								<div class="controls">
								  <?php	echo $this->formRow($form->get('user_status')); ?>
								   <span id="radioError"></span>
								</div>
							 </div>
							<div class="form-actions">
							  <?php	echo $this->formSubmit($form->get('submit')); ?>
							  <?php	echo $this->formReset($form->get('reset')); ?>
							</div>
						  </fieldset>
<?php	echo $this->form()->closeTag();	?>
<!-- End: Login Form --> 
					</div>
				</div>
			</div>
<script type="text/javascript">
	var d = new Date();
	var currentYear	= d.getFullYear();
	$("#user_dob").datepicker({
		changeYear: true,
		changeMonth: true,
		yearRange: "-100:+0",
        maxDate:  0
    });
	function clickDiv(div) {
		$('#'+div).parent().click();
	}
</script>
