<?php	/*	$carrierArray	= $this->Carriers('');
		//	FAQ Access
		if(isset($userObject->user_role_id) && $userObject->user_role_id == 3 && isset($userObject->user_access) && trim($userObject->user_access) != '') {
			$manageFaq	= (strpos('#'.$userObject->user_access.'#', '#7#') !== FALSE) ? 1 : 0;
			$manageTerms= (strpos('#'.$userObject->user_access.'#', '#8#') !== FALSE) ? 1 : 0;
			$manageContent	= 1;
		} else if(isset($userObject->user_role_id) && $userObject->user_role_id == 3) {
			$manageFaq	= 0;
			$manageTerms= 0;
			$manageContent	= 0;
		} else {
			$manageFaq	= 1;
			$manageTerms= 1;
			$manageContent	= 1;
		}	*/
		?>
<body>
	<div id="bodyDiv" style="display:none;">
	<?php	if(!isset($this->page) || !$this->page)	{ ?>

	<!-- topbar starts -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brandnew" href="<?php	echo $this->url('cms'); ?>" style="width:200px;">
					<img title="Vesta App" alt="Vesta App" style="margin-bottom:10px;margin-top:10px;margin-left:12px;" src="<?php	echo $this->basePath('images/snapstate.png'); ?>" />
				</a>
				
				<!-- user dropdown starts -->
				<div class="btn-group pull-right" >
					
					<ul class="dropdown-menu">
						<li><a href="<?php	echo $this->url('cms', array('action' => 'logout')); ?>" title="Logout">Logout</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- topbar ends -->
	<?php	} ?>
	<div class="container-fluid">
		<div class="row-fluid">
		<?php	if(!isset($this->page) || !$this->page) { ?>
		
			<!-- left menu starts -->
			<div class="span2 main-menu-span">
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet leftnavlink" onclick="location.href='<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'dashboard')); ?>';">DashBoard</li>
						<?php	if(isset($this->userObject['group_id']) && $this->userObject['group_id'] == 1) { ?>
						<li class="nav-header hidden-tablet" style="color: black; background-color: rgb(205, 205, 205);">User Management</li>
						<li class="nav-header hidden-tablet">Manage User Group</li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'carrier', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> List Group(s)</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'carrier', 'action' => 'create')); ?>"><i class="icon-th-large"></i><span class="hidden-tablet"> Create Group</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'carrier', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> User Roles</span></a></li>
						<li class="nav-header hidden-tablet">Manage User</li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'carrier', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> List User(s)</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'carrier', 'action' => 'create')); ?>"><i class="icon-th-large"></i><span class="hidden-tablet"> Create User</span></a></li>
						<?php	} ?>
						<?php	if(isset($this->userObject['group_id']) && $this->userObject['group_id'] == 1) { ?>
						<li class="nav-header hidden-tablet" style="color: black; background-color: rgb(205, 205, 205);">Media Management</li>
						<li class="nav-header hidden-tablet">Media Video</li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> List Video(s)</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'create')); ?>"><i class="icon-user"></i><span class="hidden-tablet"> Create Video</span></a></li>
						<li class="nav-header hidden-tablet">Media Category</li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> List Categories</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'create')); ?>"><i class="icon-user"></i><span class="hidden-tablet"> Create Category</span></a></li>
						<li class="nav-header hidden-tablet">Media Category</li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'list')); ?>"><i class="icon-th-list"></i><span class="hidden-tablet"> List Tag(s)</span></a></li>
						<li><a class="ajax-link" href="<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'create')); ?>"><i class="icon-user"></i><span class="hidden-tablet"> Create Tag</span></a></li>
						<?php	} ?>
						<li class="nav-header hidden-tablet leftnavlink" onclick="location.href='<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'change-password')); ?>';">Site Settings</li>
						<li class="nav-header hidden-tablet leftnavlink" onclick="location.href='<?php	echo $this->url('cms', array('controller' => 'user', 'action' => 'change-password')); ?>';">Change Password</li>
					</ul>
				</div>
			</div>
			<div id="content" class="span10">
			<?php	} ?>
