<?php	echo $this->render('leftnav.phtml'); ?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dashboard</a>
					</li>
				</ul>
			</div>
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well" style="cursor:pointer;">
						<h2><i class="icon-info-sign"></i> Introduction</h2>
					</div>
					<div class="box-content">
						<?php	if($this->userObject['group_id'] == 1) { ?>
						<h3>Welcome Admin</h3>
						<p style="margin:12px 0 34px;">You can manage the Snapstate Frond-end from this page.</p>
						<?php	} else { ?>
						<h3>Welcome</h3>
						<p style="margin:12px 0 34px;">Please manage your Site settings from here.</p>
						<?php	} ?>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
 