<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}	?>
			
			<div class="row-fluid">
				<div class="span12 center login-header">
					<h2>Welcome to Snapstate - Admin Panel</h2>
				</div><!--/span-->
			</div><!--/row-->
			<noscript>
				<div class="alert alert-block">
					<h4 class="alert-heading" style="text-align:center;">Warning!</h4>
					<p style="text-align:center;">You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			<div class="row-fluid">
				<div class="well span5 center login-box">
					<div class="alert alert-info" id="login_info">
						Please login with your Email Address and Password.
					</div>
					<div class="alert alert-error" style="<?php	echo $display; ?>">The email address or password you entered is incorrect.</div>

					<div class="alert alert-success" style="display:none;"></div>
					<div id="loginDiv">
<!-- Start: Login Form -->
<?php	$form = $this->loginForm;
		$form->setAttribute('action', $this->url('cms', array('action' => 'index')));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
					<fieldset>
							<div class="input-prepend" title="Email Address" data-rel="tooltip">
								<span class="add-on"><i class="icon-user"></i></span>
								<?php	echo $this->formRow($form->get('Email')); ?>
							</div>
							<div class="clearfix"></div>
							<div class="input-prepend" title="Password" data-rel="tooltip">
								<span class="add-on"><i class="icon-lock"></i></span>
								<?php	echo $this->formRow($form->get('Password')); ?>
							</div>
							<div class="clearfix"></div>
							<div class="input-prepend" style="margin-bottom: 0px;">
							<label class="remember" for="remember"><?php	echo $this->formRow($form->get('Remember')); ?>Remember me</label>
							</div>
							<div class="clearfix"></div>
							<div class="input-prepend">
							<a onclick="showForgetPassword();" style="cursor:pointer;">Forgot my password</a>
							</div>
							<div class="clearfix"></div>
							<p class="center span5">
							<?php	echo $this->formSubmit($form->get('submit')); ?>
							</p>
						</fieldset>
<?php	echo $this->form()->closeTag();	?>
<!-- End: Login Form -->
					</div>
					<div id="forgetPasswordDiv" style="display:none;">
<!-- Start: Forget Password Form -->
<?php	$forgetPasswordForm = $this->forgetPasswordForm;
		$forgetPasswordForm->setAttribute('action', $this->url('cms', array('action' => 'index')));
		$forgetPasswordForm->prepare();
		echo $this->form()->openTag($forgetPasswordForm);	?>
						<fieldset>
							<div class="input-prepend" title="Email Address" data-rel="tooltip" id="emailaddress">
								<span class="add-on"><i class="icon-envelope"></i></span>
									<?php	echo $this->formRow($forgetPasswordForm->get('email')); ?>
							</div>
							<div class="clearfix"></div>
							<div class="clearfix"></div>
							<p class="center span5" id="resetbuttonpart">
							<?php	echo $this->formSubmit($forgetPasswordForm->get('submit')); ?>
							</p>
							<div class="input-prepend" style="float:right; margin-top:15px; margin-bottom:0px;">
							<a onclick="showLogin();" style="cursor:pointer;">Back to Login</a>
							</div>
						</fieldset>
<?php	echo $this->form()->closeTag();	?>
<!-- End: Forget Password Form -->
					</div>
				</div><!--/span-->
			</div><!--/row-->
