<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Site Settings</a>
					</li>
				</ul>
			</div>
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well" data-original-title style="cursor:pointer;">
						<h2><i class="icon-wrench"></i> Site Settings</h2>
						<div class="box-icon">
						</div>
					</div>
					<div class="box-content">
<?php	$form = $this->siteSettingsForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'index', 'action' => 'site-settings')));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
						  <fieldset>
						  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> Site Setting updated sucessfully.</div>
							<?php	echo $this->formHidden($form->get('_id')->setAttribute('value', $siteDetails['_id']));	?>
							<div class="control-group">
								<label class="control-label" for="appId" style="width:200px;">Facebook AppID</label>
								<div class="controls" style="margin-left:220px;">
									<?php	if(isset($siteDetails['fb_app_id']) && $siteDetails['fb_app_id'] != '') { 
												$site_fbappid = $siteDetails['fb_app_id'];
											} else {
												$site_fbappid = '';
											}
											echo $this->formRow($form->get('fbappid')->setAttribute('value', $site_fbappid)); ?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="appKey" style="width:200px;">Facebook App Secret Key</label>
								<div class="controls" style="margin-left:220px;">
									<?php	if(isset($siteDetails['fb_secret_key']) && $siteDetails['fb_secret_key'] != '') { 
												$site_fbkey = $siteDetails['fb_secret_key'];
											} else {
												$site_fbkey = '';
											}
											echo $this->formRow($form->get('fbkey')->setAttribute('value', $site_fbkey));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="fbapp_name" style="width:200px;">Facebook App Name</label>
								<div class="controls" style="margin-left:220px;">
									<?php	if(isset($siteDetails['fb_app_name']) && $siteDetails['fb_app_name'] != '') { 
												$site_fbapp_name = $siteDetails['fb_app_name'];
											} else {
												$site_fbapp_name = '';
											}
											echo $this->formRow($form->get('fbapp_name')->setAttribute('value', $site_fbapp_name));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="fbpage" style="width:200px;">Facebook Page URL</label>
								<div class="controls" style="margin-left:220px;">
									<?php	if(isset($siteDetails['fb_page_url']) && $siteDetails['fb_page_url'] != '') { 
												$site_fb_page = $siteDetails['fb_page_url'];
											} else {
												$site_fb_page = '';
											}
											echo $this->formRow($form->get('fb_page')->setAttribute('value', $site_fb_page));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="timezone" style="width:200px;">Site Time Zone</label>
								<div class="controls" style="margin-left:220px;">
									<?php	if(isset($siteDetails['site_timezone']) && $siteDetails['site_timezone'] != '') { 
												$site_timezone = $siteDetails['site_timezone'];
											} else {
												$site_timezone = '';
											}	?>
								  <?php	echo $this->formRow($form->get('timezone')->setAttributes(array('value' => $site_timezone, 'style' => 'width:450px;')));	?>
								</div>
							</div>
							<div class="form-actions">
								<?php	echo $this->formRow($form->get('submit')); ?>
							</div>
						  </fieldset>
						<?php	echo $this->form()->closeTag();	?>
					</div>
				</div><!--/span-->
			</div><!--/row-->
<script type="text/javascript">
	$(document).ready(function(){
		$('div.radio').css({'margin-left':'70px'});
		$('.inline').css({'font-size':'12px'});
	});
	setTimeout("$('#userSuccessmsg').hide('slow')", 3000);
</script>
