<?php	echo $this->render('sub-header.phtml'); ?>
<dl class="row videoList" id="list_video">
	<dd class="clearfix videoMore">
    	<!-- <img src="<?php	//echo SITE_IMAGE_PATH; ?>gray_loader.gif" style="width:75px;height:75px;vertical-align:middle;margin:75px;"> -->
	</dd>                        
</dl>
<!-- <style type="text/css">
	.fb-comments, .fb-comments span[style], .fb-comments iframe[style] {width: 100% !important;}
</style> -->
<!-- <div class="fb-comments" data-href="http://snapstate.sdiphp.com" data-numposts="5" data-colorscheme="light" data-mobile="false"></div> -->
<!-- <a class="btn btn-primary btn-lg" data-toggle="modal" data-target="#change_password_form">FREE Signup!</a> -->